#!/bin/bash
mkdir -p "/workspace/scratch/jobs/earza/slurm_logs"
source scripts/array_to_string_functions.sh


EXPERIMENT_RESULT_FOLDER_NAME="/workspace/scratch/jobs/earza/${PWD##*/}"

echo "Results saved on: $EXPERIMENT_RESULT_FOLDER_NAME"


TEST_RESULT_FOLDER_NAME="$EXPERIMENT_RESULT_FOLDER_NAME/experimentResults/adapt_to_resources/results"
EXPERIMENT_CONTROLLER_FOLDER_NAME="$EXPERIMENT_RESULT_FOLDER_NAME/experimentResults/adapt_to_resources/controllers"
LOG_DIR="$EXPERIMENT_RESULT_FOLDER_NAME/logs"
SCORE_PATH="$TEST_RESULT_FOLDER_NAME/score.txt"
RESPONSE_PATH="$TEST_RESULT_FOLDER_NAME/response.txt"
TMP_RES_PATH=$EXPERIMENT_RESULT_FOLDER_NAME/"tmp"/$(dirname ${SCORE_PATH})
INSTANCES_PATH="$EXPERIMENT_RESULT_FOLDER_NAME/instances"


mkdir -p $TEST_RESULT_FOLDER_NAME
mkdir -p $EXPERIMENT_CONTROLLER_FOLDER_NAME
mkdir -p $LOG_DIR
mkdir -p $TMP_RES_PATH

cp -f -r -v "src/experiments/permus/instances/" "$INSTANCES_PATH/"


COMPILE_JOB_ID=`sbatch --parsable --exclude=n[001-004] --export=LOG_DIR=${LOG_DIR} scripts/make_hip.sh`

SRCDIR=`pwd`


NEAT_POPSIZE=1000
MAX_TRAIN_ITERATIONS=2000
MAX_TRAIN_TIME=345600
FULL_MODEL="false"
DIM=20
SOLVER_POPSIZE=8
MAX_SOLVER_FE_ARRAY=(400 1200)
i=0






# Continuous 16
train_seed=2
for param_index in 0 1; do
    CONTROLLER_NAME_PREFIX_ARRAY=()
    SEED_ARRAY=()
    COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY=()
    COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY=()
    FULL_MODEL_ARRAY=()

    MAX_SOLVER_FE="${MAX_SOLVER_FE_ARRAY[param_index]}"


    CONTROLLER_NAME_PREFIX_ARRAY+=("TrainOnlyInF_${instance_index}_seed${train_seed}_MAXSOLVERFE_${MAX_SOLVER_FE}")
    SEED_ARRAY+=("${train_seed}")
    COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY+=("1")
    COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY+=("${DIM}")
    FULL_MODEL_ARRAY+=("${FULL_MODEL}")




    CONTROLLER_NAME_PREFIX_ARRAY=$(to_list "${CONTROLLER_NAME_PREFIX_ARRAY[@]}")
    SEED_ARRAY=$(to_list "${SEED_ARRAY[@]}")
    FULL_MODEL_ARRAY=$(to_list "${FULL_MODEL_ARRAY[@]}")
    COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY=$(to_list "${COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY[@]}")
    COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY=$(to_list "${COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY[@]}")



    TRAIN_JOB_ID=`sbatch --job-name=continuous16_${MAX_SOLVER_FE} --parsable --dependency=afterok:${COMPILE_JOB_ID} --export=NEAT_POPSIZE=${NEAT_POPSIZE},SOLVER_POPSIZE=${SOLVER_POPSIZE},MAX_SOLVER_FE=${MAX_SOLVER_FE},MAX_TRAIN_ITERATIONS=${MAX_TRAIN_ITERATIONS},MAX_TRAIN_TIME=${MAX_TRAIN_TIME},SEED_ARRAY=${SEED_ARRAY},FULL_MODEL_ARRAY=${FULL_MODEL_ARRAY},COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY=${COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY},COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY=${COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY},EXPERIMENT_CONTROLLER_FOLDER_NAME=${EXPERIMENT_CONTROLLER_FOLDER_NAME},TEST_RESULT_FOLDER_NAME=${TEST_RESULT_FOLDER_NAME},LOG_DIR=${LOG_DIR},CONTROLLER_NAME_PREFIX_ARRAY=${CONTROLLER_NAME_PREFIX_ARRAY}, --array=0-$j src/experiments/real/scripts/hip_train_array_16_continuous.sl`

done




# Continuous generated
train_seed=2
for param_index in 0 1; do
    CONTROLLER_NAME_PREFIX_ARRAY=()
    SEED_ARRAY=()
    COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY=()
    COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY=()
    FULL_MODEL_ARRAY=()

    MAX_SOLVER_FE="${MAX_SOLVER_FE_ARRAY[param_index]}"


    CONTROLLER_NAME_PREFIX_ARRAY+=("Generated_seed${train_seed}_MAXSOLVERFE_${MAX_SOLVER_FE}")
    SEED_ARRAY+=("${train_seed}")
    COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY+=("0")
    COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY+=("${DIM}")
    FULL_MODEL_ARRAY+=("${FULL_MODEL}")
    NLO_ARRAY+=("2")




    CONTROLLER_NAME_PREFIX_ARRAY=$(to_list "${CONTROLLER_NAME_PREFIX_ARRAY[@]}")
    SEED_ARRAY=$(to_list "${SEED_ARRAY[@]}")
    FULL_MODEL_ARRAY=$(to_list "${FULL_MODEL_ARRAY[@]}")
    COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY=$(to_list "${COMMA_SEPARATED_PROBLEM_INDEX_LIST_ARRAY[@]}")
    COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY=$(to_list "${COMMA_SEPARATED_PROBLEM_DIM_LIST_ARRAY[@]}")

    NLO_ARRAY=$(to_list "${NLO_ARRAY[@]}")


    # launch training and get JOB_ID to queue test to launch only after training is complete
    TRAINING_JOB_ID=`sbatch --job-name=generated_${MAX_SOLVER_FE} --parsable --dependency=afterok:${COMPILE_JOB_ID} --export=MAX_TRAIN_TIME=$MAX_TRAIN_TIME,MAX_TRAIN_ITERATIONS=$MAX_TRAIN_ITERATIONS,NEAT_POPSIZE=$NEAT_POPSIZE,CONTROLLER_NAME_PREFIX_ARRAY=$CONTROLLER_NAME_PREFIX_ARRAY,EXPERIMENT_CONTROLLER_FOLDER_NAME=$EXPERIMENT_CONTROLLER_FOLDER_NAME,SEED_ARRAY=$SEED_ARRAY,NLO_ARRAY=$NLO_ARRAY,DIM=$DIM,SOLVER_POPSIZE=$SOLVER_POPSIZE,MAX_SOLVER_FE=$MAX_SOLVER_FE,FULL_MODEL=$FULL_MODEL --array=0-$i src/experiments/real/scripts/hip_train_array_random_problem.sl`


done





# Permus
train_seed=2
PROBLEM_TYPE="tsp"
PROBLEM_PATH="$INSTANCES_PATH/transfer_permuproblems/tsp/ch130.tsp"

for param_index in 0 1; do
    PROBLEM_TYPE_ARRAY=()
    CONTROLLER_NAME_PREFIX_ARRAY=()
    SEED_ARRAY=()
    
    PROBLEM_TYPE_ARRAY+=("${PROBLEM_TYPE}")
    COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY+=("${PROBLEM_PATH}")
    CONTROLLER_NAME_PREFIX_ARRAY+=("Permus_seed${train_seed}_MAXSOLVERFE_${MAX_SOLVER_FE}")
    SEED_ARRAY+=("${train_seed}")
    MAX_SOLVER_FE="${MAX_SOLVER_FE_ARRAY[param_index]}"


    SEED_ARRAY=$(to_list "${SEED_ARRAY[@]}")
    PROBLEM_TYPE_ARRAY=$(to_list "${PROBLEM_TYPE_ARRAY[@]}")
    COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY=$(to_list "${COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY[@]}")
    CONTROLLER_NAME_PREFIX_ARRAY=$(to_list "${CONTROLLER_NAME_PREFIX_ARRAY[@]}")


    TRAINING_JOB_ID=`sbatch --job-name=permus_${MAX_SOLVER_FE} --parsable --dependency=afterok:${COMPILE_JOB_ID} --export=PROBLEM_TYPE_ARRAY=$PROBLEM_TYPE_ARRAY,COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY=$COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY,SEED_ARRAY=$SEED_ARRAY,NEAT_POPSIZE=$NEAT_POPSIZE,MAX_SOLVER_FE=$MAX_SOLVER_FE,SOLVER_POPSIZE=$SOLVER_POPSIZE,MAX_TRAIN_ITERATIONS=$MAX_TRAIN_ITERATIONS,MAX_TRAIN_TIME=$MAX_TRAIN_TIME,EXPERIMENT_CONTROLLER_FOLDER_NAME=${EXPERIMENT_CONTROLLER_FOLDER_NAME},TEST_RESULT_FOLDER_NAME=${TEST_RESULT_FOLDER_NAME},LOG_DIR=${LOG_DIR},CONTROLLER_NAME_PREFIX_ARRAY=${CONTROLLER_NAME_PREFIX_ARRAY} --array=0-$i src/experiments/permus_multi/scripts/hip_train_multi_array.sl`


done



# QAP
train_seed=2
PROBLEM_TYPE="qap"
PROBLEM_PATH="$INSTANCES_PATH/transfer_qap_cut_instances/A3_cut40_tai60a.qap"
for param_index in 0 1; do
    PROBLEM_TYPE_ARRAY=()
    CONTROLLER_NAME_PREFIX_ARRAY=()
    SEED_ARRAY=()
    
    PROBLEM_TYPE_ARRAY+=("${PROBLEM_TYPE}")
    COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY+=("${PROBLEM_PATH}")
    CONTROLLER_NAME_PREFIX_ARRAY+=("Qap_seed${train_seed}_MAXSOLVERFE_${MAX_SOLVER_FE}")
    SEED_ARRAY+=("${train_seed}")
    MAX_SOLVER_FE="${MAX_SOLVER_FE_ARRAY[param_index]}"


    SEED_ARRAY=$(to_list "${SEED_ARRAY[@]}")
    PROBLEM_TYPE_ARRAY=$(to_list "${PROBLEM_TYPE_ARRAY[@]}")
    COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY=$(to_list "${COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY[@]}")
    CONTROLLER_NAME_PREFIX_ARRAY=$(to_list "${CONTROLLER_NAME_PREFIX_ARRAY[@]}")


    TRAINING_JOB_ID=`sbatch --job-name=qap_${MAX_SOLVER_FE} --parsable --dependency=afterok:${COMPILE_JOB_ID} --export=PROBLEM_TYPE_ARRAY=$PROBLEM_TYPE_ARRAY,COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY=$COMMA_SEPARATED_LIST_OF_INSTANCE_PATHS_ARRAY,SEED_ARRAY=$SEED_ARRAY,NEAT_POPSIZE=$NEAT_POPSIZE,MAX_SOLVER_FE=$MAX_SOLVER_FE,SOLVER_POPSIZE=$SOLVER_POPSIZE,MAX_TRAIN_ITERATIONS=$MAX_TRAIN_ITERATIONS,MAX_TRAIN_TIME=$MAX_TRAIN_TIME,EXPERIMENT_CONTROLLER_FOLDER_NAME=${EXPERIMENT_CONTROLLER_FOLDER_NAME},TEST_RESULT_FOLDER_NAME=${TEST_RESULT_FOLDER_NAME},LOG_DIR=${LOG_DIR},CONTROLLER_NAME_PREFIX_ARRAY=${CONTROLLER_NAME_PREFIX_ARRAY} --array=0-$i src/experiments/permus_multi/scripts/hip_train_multi_array.sl`


done



