#pragma once
#include <limits.h>

#define MAX_EVALS_PER_CONTROLLER 400
#define MAX_EVALS_PER_CONTROLLER_REEVAL 5000

#define N_EVALS_PER_CONTROLLER_SELECT_BEST_IN_REINITIALIZATION 10000
#define REINITIALIZE_CONTROLLERS_EVERY_N_ITERATIONS 501

#define use_same_seed_every 72


#define MAX(A, B) ((A > B) ? A : B)
#define MIN(A, B) ((A < B) ? A : B)

#define SMALLEST_POSITIVE_DOUBLE  10e-70

#define TEMP_double_ARRAY_SIZE 30


#define DEPTH_OF_ORDER_MARGINAL 4
#define COMPUTE_ORDER_MARGINAL_EVERY_K_ITERATIONS 0





#define CUTOFF_0 0.25


#define LENGTH_CHANGE_STEP 5